using System.Collections.Generic;
using TarotApi.Domain.Models;

namespace TarotApi.Infrastructure.Models
{
    public class RiderWaiteDeck
    {
        public List<Card> Cards { get; private set; }

        public RiderWaiteDeck()
        {
            Cards = new List<Card>()
            {
                //MAJOR ARCANA
                new Card("The Fool",
                         "https://upload.wikimedia.org/wikipedia/en/9/90/RWS_Tarot_00_Fool.jpg",
                         "Innocence, Beginnings, Adventure",
                         "Naiveté, Recklesness, Gullible"),
                new Card("The Magician",
                         "https://upload.wikimedia.org/wikipedia/en/d/de/RWS_Tarot_01_Magician.jpg",
                         "Willpower, Creation, Mastery",
                         "Manipulation, Destruction, Untapped Potential"),
                new Card("The High Priestess",
                         "https://upload.wikimedia.org/wikipedia/en/8/88/RWS_Tarot_02_High_Priestess.jpg",
                         "Intuition, Inner Voice, Spirituality",
                         "Confusion, Repressed Inner Voice, Superficiality"),
                new Card("The Empress",
                         "https://upload.wikimedia.org/wikipedia/en/d/d2/RWS_Tarot_03_Empress.jpg",
                         "Fertility, Nurturing, Abundance",
                         "Negligence, Smothering"),
                new Card("The Emperor",
                         "https://upload.wikimedia.org/wikipedia/en/c/c3/RWS_Tarot_04_Emperor.jpg",
                         "Stability, Authority, Protection",
                         "Rigid, Domineering, Tyranny"),
                new Card("The Hierophant",
                         "https://upload.wikimedia.org/wikipedia/en/8/8d/RWS_Tarot_05_Hierophant.jpg",
                         "Tradition, Conformity, Knowledge",
                         "Rebellion, Non-conformity, Ignorance"),
                new Card("The Lovers",
                         "https://upload.wikimedia.org/wikipedia/en/d/db/RWS_Tarot_06_Lovers.jpg",
                         "Love, Partnerships, Unity",
                         "Detachment, Disharmony, Conflict"),
                new Card("The Chariot",
                         "https://upload.wikimedia.org/wikipedia/en/9/9b/RWS_Tarot_07_Chariot.jpg",
                         "Victory, Ambition, Determination",
                         "Forceful, No control, Aggression"),
                new Card("Strength",
                         "https://upload.wikimedia.org/wikipedia/en/f/f5/RWS_Tarot_08_Strength.jpg",
                         "Strength, Courage, Inner Power",
                         "Weakness, Self-Doubt, Cowardice"),
                new Card("The Hermit",
                         "https://upload.wikimedia.org/wikipedia/en/4/4d/RWS_Tarot_09_Hermit.jpg",
                         "Introspection, Solitude, Contemplation",
                         "Isolation, Loneliness, Recluse"),
                new Card("The Wheel of Fortune",
                         "https://upload.wikimedia.org/wikipedia/en/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
                         "Important Changes, Cycles, Fate, Luck",
                         "Back Luck, Unwelcome Changes, Delays"),
                new Card("Justice",
                         "https://upload.wikimedia.org/wikipedia/en/e/e0/RWS_Tarot_11_Justice.jpg",
                         "Justice, Karma, Consequence, Truth",
                         "Injustice, Retribution, Corruption"),
                new Card("The Hanged Man",
                         "https://upload.wikimedia.org/wikipedia/en/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
                         "Sacrifice",
                         "Selfishness, Apathy"),
                new Card("Death",
                         "https://upload.wikimedia.org/wikipedia/en/d/d7/RWS_Tarot_13_Death.jpg",
                         "Transformation, Endings, Letting Go",
                         "Fear of Change, Stagnancy, Decay"),
                new Card("Temperance",
                         "https://upload.wikimedia.org/wikipedia/en/f/f8/RWS_Tarot_14_Temperance.jpg",
                         "Balance, Moderation, Patience",
                         "Imbalance, Excess, Hastiness"),
                new Card("The Devil",
                         "https://upload.wikimedia.org/wikipedia/en/5/55/RWS_Tarot_15_Devil.jpg",
                         "Obsession, Oppression, Materialism",
                         "Independence, Freedom, Reclamation of Power"),
                new Card("The Tower",
                         "https://upload.wikimedia.org/wikipedia/en/5/53/RWS_Tarot_16_Tower.jpg",
                         "Destruction, Hubris, Disaster",
                         "Averting Disaster, Delaying the Inevitable"),
                new Card("The Star",
                         "https://upload.wikimedia.org/wikipedia/en/d/db/RWS_Tarot_17_Star.jpg",
                         "Hope, Inspiration, Rejuvenation",
                         "Hopelessness, Despair, Negativity"),
                new Card("The Moon",
                         "https://upload.wikimedia.org/wikipedia/en/7/7f/RWS_Tarot_18_Moon.jpg",
                         "Illusion, Duality, Secrets",
                         "Misunderstanding, Anxiety, Confusion"),
                new Card("The Sun",
                         "https://upload.wikimedia.org/wikipedia/en/1/17/RWS_Tarot_19_Sun.jpg",
                         "Happiness, Vitality, Optimism",
                         "Unrealistic Expectations, Pessimism, Blocked Happiness"),
                new Card("Judgement",
                         "https://upload.wikimedia.org/wikipedia/en/d/dd/RWS_Tarot_20_Judgement.jpg",
                         "Judgement, Self-evaluation, Reckoning",
                         "Lack of Self-Awareness, Failure to Learn Lessons"),
                new Card("The World",
                         "https://upload.wikimedia.org/wikipedia/en/f/ff/RWS_Tarot_21_World.jpg",
                         "Completion, Fulfillment, Belonging",
                         "Incompletion, Emptiness, Lack of Closure"),
            };
        }
    }
}
